### ISSUE TITLE
Nullable Suggester Response

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/JMusicBot#31]
```java
@Nonnull
Song suggestNext();
```

Suggester#suggestNext() is marked as Nonnull, but i can see plenty of cases where an optional or a nullable response would be preferable. (Empty Playlist, No Songs to build radio upon)

**Comment by BjoernPetersen** [comment]
Those problems should be detected while initializing

**Comment by BjoernPetersen** [comment]
I'll think about some kind of BrokenSuggesterException though

**Comment by FelixGail** [comment]
Pausing the bot on empty suggestions would be the other options. i can't listen to Mickie Krause anymore

**Comment by BjoernPetersen** [comment]
You're right, me neither. I'll create a checked exception for suggestNext and getSuggestions
